novus/nvd3

examples/indentedtree.html

Great work on nvd3. I'm using it at a green-tech start-up to chart electricity consumption...
1. Update link to nvd3,org home page.
2. Make all links to other examples relative, so they won't break so easily.

Fix broken links in indentedtree.html

---

src/interactiveLayer.js

instanceof has a higher precedence than the ! operator, so this is needed, otherwise you're just calling 'true instanceof Array' or 'false instanceof Array' which are both always false.

Add ()'s so that instanceof check works as intended

---

README.md
bower.json
src/interactiveLayer.js
test/mocha/utils.coffee

As of D3 commit:
https://github.com/mbostock/d3/commit/3c7cc81b6233289263525b581d635ad9f8d9dd37
We are no longer able to use an array accessor that accepts two
parameters (the second being the index of the first parameter in the
given array), since d3.bisector() will consider it a comparison
function instead of an accessor.
There does not appear to be a way to get the index value of the element
being considered in the context of the accessor.
As a result, this commit proposes we drop the interactiveBisect()
support for accessors accepting a second parameter being the index of
the first in a given array.
We now wrap all x-accessors passed to interactiveBisect() hiding the
second parameter, using an internal comparator instead.
This commit also attempts to get the coverage to 100% for …

Move minimum D3 version to 3.4.4

---

src/models/scatterChart.js
test/mocha/bullet.coffee
test/mocha/cumulative-line.coffee
test/mocha/discretebar.coffee
test/mocha/historical-bar.coffee
test/mocha/line.coffee
test/mocha/multibar-horizontal.coffee
test/mocha/multibar.coffee
test/mocha/pie.coffee
test/mocha/scatter.coffee
test/mocha/sparkline.coffee
test/mocha/stacked.coffee

Refs #785
Every other chart has this. Needed to have chart.options() be the standard way to access a chart's options.

Add options function binding to scatterChart

---

src/models/bulletChart.js
src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBar.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/lineWithFocusChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/multiChart.js
src/models/ohlcBar.js
src/models/parallelCoordinates.js
src/models/pieChart.js
src/models/scatter.js
src/models/scatterChart.js
src/models/sparklinePlus.js
src/models/stackedAreaChart.js
src/utils.js
test/mocha/utils.coffee

This is an attempt to make it easier for callers to figure out chart sizing, while reducing duplicate code of such calculations.
The angularjs-nvd3-directives project issues https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/issues/56, and https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/issues/11, show that initial need.

Expose utils methods of container sizing and available dimensions

---

README.md
package.json

Fixes a syntax typo for D3 peerDependencies in package.json and makes it the same as specified in bower.json .
Also combines duplicate (and wrong) version dependencies in README.
Removes the reference to Interactive guideline tooltip bug that was fixed per #760 that is also related to D3 version.

d3 version fix in README and package.json

---

src/models/stackedAreaChart.js
test/mocha/stacked.coffee

Pull Request #790 introduced another bug, where if you switch to 'Expanded'
and then switch back to 'Stacked', the yAxis retains the percentage format.
Fixed bug and added unit test.

Stacked Area: yAxis formatting bug (percentage format sticks)

---

src/nv.d3.css

If a chart is displayed on a page with white text, the tool-tips become unreadable. I have added two lines of CSS to ensure that the tool-tip's text is displayed in black so that it can be read.

Added text colour  so that tooltips display correctly when on pages with white text.

---

src/models/pie.js

Fixes #801. Only set start and end angles if they're specified. Explicitly equate with `false` because `0` is a valid angle. `false`, on the other hand, is not a valid angle until it gets coerced to `0`. The problem was that the labels were being put on an arc of zero angular length.

Fix donut chart labels.

---

examples/documentation.html
examples/pieChart.html
src/core.js
src/models/pie.js
src/models/pieChart.js

Also cleaned up the code a little, and changed the labelsOutside options to just be a single option and added depreciated stubs for the old options that gives console warnings.  Also changed it so depreciated warnings show up even if not in dev mode since they're pretty important.
Current charts that override tooltipContent will see their tooltips break though.   There isn't a lot I can do about that since the way it was passing the data was stupid because it was picking out parts instead of just passing the whole event object.

Change pie/donut charts to use a mouse following tooltip

---

src/models/lineWithFocusChart.js

Change the lines.duration to 0, to remove transitions and prevent weird things from happening when changing the focus area.
Issue #816

Issue #816:  lineWithFocusChart, fixing the 'wiggling'

---

examples/donutChart.html
src/models/pie.js

Adjust automatically the font-size of the title, with respect to the current donut chart size.
- It's not necessary to define a size in a css.
- It supports resizing.
- it depends on the title length
- it takes into account the donut ratio.

Pie title supports resizing.

---

src/interactiveLayer.js
src/tooltip.js

- Enable interactiveLayer mouseHandler on touch event
- Fixed position of tooltip in touch browser, because webkit does not support `transform` which makes tooltips to appear on the top left corner

Basic support in touch browser

---

examples/documentation.html
examples/parallelCoordinates.html
src/css/parallelcoordinates.css
src/models/parallelCoordinates.js

- Support missing values : Missing values cannot be displayed per definition, since they are missing. Nevertheless, they also provide useful information when trying to understand the data. The option proposed is to exploit the available horizontal space to introduce a third dimension outside of the normal range. Whenever a displayed row has a missing value in one dimension, the connecting line falls out of the regular space and falls onto the missing value axis.
Ref:  http://informationandvisualization.de/blog/parallel-coordinates-and-missing-values
- Support only one line displayed (Fix)
- Possibility to define a tickFormat for each axis

ParallelCoordinate support missing values.

---

examples/documentation.html
src/interactiveLayer.js
src/tooltip.js

If you use chartContainer on normal tooltips, don't do special calculations intended for the interactive layer tooltip.  This fixes the tooltip position issue from https://github.com/novus/nvd3/issues/893
The added option should never be used by anything other than interactive guideline so I prefixed it with an underscore and set the documentation to ignore options starting with an underscore.

Fix tooltip position to be correct if you use chartContainer

---

src/core.js

I encountered the memory leak when ajax refreshing in data for a continuously updating dashboard. It was only glaring for me because I had eight graphs of time series data on a single page and got to the dead browser screen pretty quick. Commenting out seems the right immediate fix as the array isn't used. Longer term if nv.graphs is desired, you'd have to make sure it stayed a fixed size -- splicing off as you go.

nv.graphs is never emptied -- mem leak w/refreshed data on page

---

.travis.yml
package.json

Followup of #919.
Having `bower install` in the postinstall hook makes this library not possible to install through npm in environments where bower is not available.
To keep compatibility with travis, `bower install` is now invoked after npm install in the travis.yml

Remove bower install from postinstall hook

---

examples/lineWithFocusChart.html
src/models/lineWithFocusChart.js

Integrated the `useInteractiveGuideline` function from the existing linechart into lineChartWithFocus.
Used pull request https://github.com/novus/nvd3/pull/336 that wasn't merged, because it became stale, as a reference.
To see in action you need to build as I've not checked in any of the
build folder js and css as per the Contributing instructions.

Added useInteractiveGuideline to lineWithFocusChart

---

src/models/axis.js

Done in order to distinguish between the minimum and maximum labels on the x and y axes, the existing css class, being 'nv-axisMaxMin' remains in place, and default formatting remains as-is.
Additional Classes Referenced in the X Axis Min/Max Values
Min X: nv-axisMaxMin-x, nv-axisMin-x
Max X: nv-axisMaxMin-x, nv-axisMax-x
Additional Classes Referenced in the Y Axis Min/Max Values
Min Y: nv-axisMaxMin-y, nv-axisMin-y
Max Y: nv-axisMaxMin-y, nv-axisMax-y
The actual class implementations are not made in the CSS file, and have simply been added to the plot area HTML in to give the user an additional means to tailor their formatting via their custom CSS file.
Cheers.
NH

Added Additional Reference to CSS Classes for Min/Max Labels

---

src/models/pieChart.js

This seems to fix the bugginess in issue #862; it adjusts as the browser window in sized up and down and doesn't translate the legend way off to the right on first load.
I couldn't get a good example working in jsfiddle because of all the resizing, but i created [this gist](https://gist.github.com/rreinhardt9/6b055863fcf41c76a5ce) that can be used to try it out locally.
I wanted to open this PR for discussion, like I mentioned in the issue I'm pretty new to nv and d3.
Thanks!

Fix #862, legend position 'right' buggy

---

src/css/tooltip.css

For some reason, the value of the border-top-left-radius property was
different than the value of the webkit and mozilla versions of the
property (1px vs 5px).
This is just like the earlier #956, but now against the development 
branch (sorry for the noise!).

Fix the border-top-left-radius property of .nvtooltip h3.

---

src/models/historicalBarChart.js

Just needed to add 'tooltipHide' to list of dispatch functions in the historicalBarChart.js file. #952

fix historicalBarChart tooltip not hidding when moused out, #952

---

GruntFile.js
examples/candlestick.html
examples/candlestickChart.html
examples/site.html
src/css/candlestick.css
src/models/candlestickBar.js
src/models/historicalBarChart.js
src/models/ohlcBar.js

As I can't bear seeing the ugly ohlc chart (the chart is ugly, not nvd3's implementation), I decided to implement a candlestick chart based on the existing ohlc chart.
It is fully working, ready to merge, with the examples created. This can be merged before the 1.8.x release.
I only don't know where can I update the example page on github pages, it is only missing that.
Any comments on the implementation are appreciable.
Oh, and also fixed a bug with the ohlc chart that some bars are clipped or overlap with the Y axis.
Screenshot:

Candlestick Chart

---

examples/documentation.html
src/models/sunburst.js

Right now, the size of the 'pieces' of the sunburst chart is not respective to their data, but to the number of children of a given parent.
This commit adds an option "mode", that allows the user to choose the two modes as illustrated 
[here](http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad).
As an added bonus, one can now display the sum of the children's values in the tooltip of a given parent node as follows:
```
chart.sunburst.dispatch.on('elementMouseover.tooltip', function(evt) {
evt['series'] = {
key: evt.data.name,
value: evt.data.value,
color: evt.color
};
chart.tooltip.data(evt).hidden(false);
});
```

Added option to SunburstChart to scale to size, not only count

---

src/models/sunburstChart.js

This PR exposes the 'tooltip' public variable of the SunburstChart, in order to be consistent with the other charts which expose the 'tooltip' as well.

SunburstChart: Expose 'tooltip' public variable

---

src/models/stackedAreaChart.js

Bug: when calling chart.update() in expanded view and then switching to another view the yTickFormat remains the percentage format.
Fix: only set oldYTickFormat when changing from another view to expanded (and not when remaining in expanded view).

StackedAreaChart: Fix wrong yAxis tickFormat on chart.update() in Expanded view

---

src/models/sunburst.js

This commit adds a new event handler that resets to the actual root node (from the data perspective) on doubleclick.
Originally I wanted to make it so that it would only happen if you doubleclick on the current root node with a check in the doubleclick handler for `if (node === d)`, but that doesn't work since a double click also fires a single "click" event, which does `node = d` already. This causes the `if` to always be true. 
So now it resets if you double click on any node, which works for my purposes, but I'm open for suggestions on how to make it behave like I described earlier.

Sunburst: Reset to actual root node on double click

---

src/models/sunburstChart.js

When setting duration on a SunburstChart object, it should also set the duration of the underlying sunburst object.

SunburstChart: Fix setting duration

---

examples/bulletChart.html
src/models/bullet.js
test/mocha/bullet.coffee

Currently, the API shows that we can provide an array of markers and labels to the bulletChart but unfortunately, it only displays the first marker.
This adds the ability to pass an array of markers and an array of labels and have them all show up.
I'm happy to make any changes that are recommended, this was just my first pass when I needed this feature.
I'm also happy to squash all the commit messages, I just assume there will be some feedback first so I thought I'd wait!
Thanks!

Allow multiple markers and labels on bullet chart

---

src/models/lineWithFocusChart.js

* Fix x- and yTickFormat not calling correct functions on Axis
* Fix duration not being set on x2Axis and y2Axis

LineWithFocusChart: Fix setting tickFormat, duration

---

src/models/pie.js

Hey guys I noticed a bug in the pie chart when you specify the labelType as percent.
Here is a before and after of the problem:

Fix percent bug in pie chart

---

src/models/pie.js

Fixed bug #861 
Had to change the logic to not create an entire new arc object and instead use the one already created before settings its innerRadius to zero.
Here is a before and after:

fixed pie/donut chart wrong label positions bug

---

src/models/stackedAreaChart.js

allowing users to set valueFormatter for interactiveLayer.tooltip (it
was previously being overwritten)
This change should also be implemented on other charts that use
interactiveLayer.tooltip
Newer iteration of #986
I believe I found a fix using the same method `yAxis.tickFormat` uses.
See [this plunk](http://plnkr.co/edit/RGxg04vhFvGl3uLTJ3Cy?p=preview).

fixing stackedArea tooltip formatting

---

src/models/stackedAreaChart.js

stackedAreaChart defines `cData = ['Stacked','Stream','Expanded']`, but
does not provide accessors. Users can't select which to show and need to
choose to display all or none of the controls. Also, it seems the
'Stack_Percent' option can currently never be set.
[Example Plunk](http://plnkr.co/edit/fj83zH2vdOYOfniG5UVK?p=preview) without "Stream" shown

exposing get/set stackedAreaChart controls

---

src/models/stackedArea.js

[Example plunk](http://plnkr.co/edit/yQ6iswJOJVrcmfa9n4dH?p=preview)
Differentiating between 'expand' and 'stack_percent'.
expand: all 0's --> 33.33% each
stackedPercent: all 0's --> 0% each
expand: filtering causes other series to expand to 100%
stackedPercent: filtering removes other series, but their percent values
remain the same
Accomplishes previously desired behavior without the bug in #945
An addition to #950

creating expanded for stackedArea

---

src/models/stackedAreaChart.js

This patch modifies how we assign the yAxis valueFormatter so we don't
overwrite the original yAxis with out percent formatter.

Fixes: #1014.

---

src/models/multiBar.js

- Removing duplicate declaration of 'parsed' 
- In stacked mode, clicking the lastly positioned serie's legend throws an error. It was trying to access the deleted reference. I added a null check.

Bug fixes for multiBar model

---

src/models/bulletChart.js

This is an enhancement resolving #1052
I have to idea how to write a test for this, sorry about that.
One thing I've noticed that the number of ticks won't be exact in some cases.
I've tried the bulletChart example (the last one with custom labels) with
ticks(2) -> result is 2 ticks
ticks(3) -> result is 4 ticks
ticks(5) -> result is 7 ticks
ticks(10) -> result is 7 ticks
ticks(20) -> result is 16 ticks
ticks(30) -> result is 30 ticks
I assume it is related to the d3.js ticks function.

created an option to configure the number of ticks for bulletChart

---

README.md

Correction to a closed pull request: novus/nvd3/pull/1034
liquidpele was right that `bower install` is required to run tests, not to build project

bower install is required to run unit tests

---

src/models/scatterChart.js
test/mocha/scatter.coffee
test/mocha/test-utils.coffee

I was able to reproduce #1025 reliably with these steps:
1. Use a data object where each series does not have a `color` attribute set (ex. series A, B, C)
2. Hover over a point from series A to display the tooltip
3. Cause a chart update (clicking a legend item, resizing the browser window)
4. All colors will shift to the right (B has A's color and C has B's color)
The problem:
The tooltip function needs a series color to display, so it sets the series A color using the color(d, i) function.
Then, when the chart is updated, series A has a color. In the current scatterChart model, if a series has a color then the color function is not called. So, color(d, i) is called for the first time to get the color for series B. Thus, B gets the first color (the color that A had on the first draw).
I …

fix for issue 1025

---

src/models/sparklinePlus.js

Hello... I'm not entirely sure why, but the old sparklinePlus update code was causing the error "cannot read property '1' of undefined" in our application when I would bind resize to chart update `nv.utils.windowResize(chart.update);`.  In this case, it would work on first load but on resize the error would occur. Changing the function to be consistent with the other models and use `container.call(chart);`  fixes the issue in our app.
[Here](http://rreinhardt9.github.io/d3_workshop/broken_sparkline.html) is a mockup using the latest on the development branch; open up the console and then resize the window and you'll see what I mean. This is pretty much the example form the sparklinePlus example page, but I added `.transition()` before calling the chart. Adding this is what seems to cause …

Change sparklinePlus update function to be consistent with other models

---

examples/multiChart.html
src/models/multiChart.js

I've been using multiChart for lines and bars, but I'd also like to add scatters to my charts. This request extends the multiChart.js model and multiChart.html example to support scatters as well.
Since we're just adding a scatter model to the multiChart model, scatter.coffee provides unit test coverage. I've updated the multiChart.html example and inspected visually. It works as expected; I don't see any glaring errors.
Thanks for reviewing! Let me know if you have any feedback

Feature: add scatters to multiChart model

---

src/models/linePlusBarChart.js
src/models/lineWithFocusChart.js

A line-with-focus-chart or a line-plus-bar-chart will essentially
duplicate the number of lines and points drawn on the screen because
there are two copies of an nv.models.line maintained.  We only need
the scatter points for the main chart, the focus chart will never
use them.  This can save a lot of memory and CPU when rendering
graphs with large data sets.

Turn off scatter pts in focus charts

---

examples/lineWithFocusChart_x2AxisLabel.html
src/models/linePlusBarChart.js
src/models/lineWithFocusChart.js

If one would want to place an x-axis label below both the graph and its
focus graph, prior to this patch it is not possible in a fixed height
setting, as there is no way to change the bottom margin to account for
a label.
This change adds the ability to change the bottom margin.  Note that in
order for that label to work while maintaining the focus graph height,
one also has to up the "focusHeight" value.

Add ability to change lwfc focus graph margins

---

src/models/linePlusBarChart.js

Prior to these changes when you disabled the first line any other line
that was enabled also disappeared from the chart. Disabling any line
except for the first also resulted in the disabled line still appearing
on the chart but with the first line's color.
Fixes #463.

Fix linePlusBarChart to better handle having multiple lines.

---

src/css/tooltip.css
src/models/stackedAreaChart.js
src/tooltip.js

Stacked area plots are used when you want to understand how various parts add up to a whole, and how this breakdown varies with respect to some *x* dimension. So you often want to know what the whole is. This change adds a **TOTAL** row at the bottom of the `stackedAreaChart` tooltip.
`examples/stackedAreaChart.html` works well and looks like:

Added 'TOTAL' to stackedAreaChart tooltip.

---

src/utils.js

Always use 'null' to call available{Width,Height} when creating
the noData container so that the the proper width and height
is calculated from the container.
Otherwise the value from the chart options would be used, 
which might not have been overridden.

Fix noData container placement

---

src/models/stackedArea.js

Fix for Issue #1093, still get warnings when a user clicks on an area in the chart but no errors occur and all functionality is there.

Fixed TypeError bug when a user clicks on an area of a stacked area chart, Issue #1093

---

src/tooltip.js

Okay, I'm trying this again after fixing that build issue.
This is a one-line fix for Issue #1124. As I said there, the tooltip with 'w' gravity was jumping down when it hit the top of the window, instead of staying at the top. (The problem did not exist when the tooltip hit the bottom of the window).
If you look at the switch statement that calculates the 'top' for each of the four gravity types, it's pretty clear that the 'top' formula for 'w' was accidentally taken from the 'left' formula for 'n' and 's'. My fix simply makes the 'top' formula for 'w' the same as the 'top' formula for 'e'.
Before and after pics are attached. The important points in the pics are the location of the mouse vs. the location of the tooltip.
Thanks much,
Jake
Before: tooltip jumping down when it hits top of …

initial commit (to src instead of build)

---

package.js

I think meteor's atmosphere is still showing version 1.7.1 because the package `1.8.1-dev` does not exist as a tag or branch on this repository. I think this change will allow meteor to update to 1.8.1, but I'm not 100% sure. Anyway, it seems sensible to have a version number which exists rather than one which does not, so the change won't do any harm.

Meteor: Specify package which matches git tag

---

src/tooltip.js

Add case 'center' for the tooltip showing. Useful when user want to show the tooltip center.

Add case 'center' to calcTooltipPosition.

---

examples/furiousLegend.html
examples/legend.html
src/models/furiousLegend.js
src/models/legend.js
src/tooltip.js

This fix provides an additional variable to set a fixed max key length
value to truncate any legend key values with lengths over the specified
threshold. This provides the option to organize legend keys to be seen
in a more readable manner.
Added tooltip for truncated legend text.
When mousing over truncated text within the legend,
a tooltip showing the full key value is revealed.

Added maxKeyLength variable to truncate legend key values.

---

examples/documentation.html
src/tooltip.js

The documentation says the default margin for all charts is 0 in all dimensions - which isn't correct.
This change instantiates the chart and pulls the default margin off of it, and then serializes that to a string to show as the documentation.
This pattern could probably be used for some other pieces of documentation, but I don't have an exhaustive enough knowledge of the library to know where it would be useful.

Documentation Fix for Default Margins

---

src/tooltip.js

Added extra tween for the -webkit-transform style attribute, so that in Safari (and Qt5.3+ applications using Qt webkit), the tooltips do not appear to fly in from the origin. This does not appear to impact other browsers in any way. 
Could not find an existing test for this, so please let me know if one needs to be added and where.

Fixed tooltip transform style interpolation issue under Safari

---

src/models/lineWithFocusChart.js

Classed was only being applied to the focus control chart and lost on the main chart as it was overwritten. This bug fix allows styling of the line series in the main chart.
Prior to Bug Fix:
Fixed:

BugFix: Don't loose classed for main chart in lineWithFocusChart

---

src/models/multiBarHorizontal.js

This commit is related with the issue :
Multibarhorizontal show width 1 when the data is undefined, I think that the width should be 0 #1216

return 0 when the y value is undefined

---

src/models/discreteBar.js

Fixed bug where, when yDomain[0] is negative, bars are too tall (since the subtraction is based on y(yDomain[0]) instead of y(0)).

Fixed bug when yDomain[0] is negative

---

src/models/lineChart.js

`historicalBarChart` has this data but it was missing in the lineChart.
Adding this enables the use of that data when creating a custom tooltip.
Here's a example.
```js
var tsFormat = d3.time.format('%b %-d, %Y %I:%M%p');
var contentGenerator = chart.interactiveLayer.tooltip.contentGenerator();
var tooltip = chart.interactiveLayer.tooltip;
tooltip.contentGenerator(function (d) { d.value = d.series[0].data.x; return contentGenerator(d); });
tooltip.headerFormatter(function (d) { return tsFormat(new Date(d)); });
```
Notice the `d.value = d.series[0].data.x` in the `tooltip.contentGenerator`, this was not available before in the lineChart.

Add series data to allData in lineChart.

---

src/models/lineChart.js

This is a style-only change set - it just fixes a bunch of as missing ; and avoids using non-coercive comparisons (=== !==) to null

jslint fixes for lineChart

---

composer.json

Adding a composer.json file brings nvd3 into line with d3 and its use of
composer files. This will allow PHP and any projects using composer to
more easily integrate the nvd3 library like that do with d3.

Added composer file to allow easier deployment

---

src/models/lineChart.js

There's two meaningful fixes here:
1. The interactive tooltip's header had been using the xAxis tickFormat.  Instead, use the formatter that's associated with the tooltip.  It's a no-op for folks who have not custom-set the tooltip headerFormat.
2. While auditing to find that fix, I noticed that the data value being used was indexed into series and not currentValues.  currentValues is a filtered copy of series, so there's a subtle bug.

Use tooltip formatter for interactiveGuideline instead of axisFormatter

---

examples/documentation.html
src/models/lineChart.js
src/models/scatter.js

When lineChart was unified with lineWithFocusChart, a bug crept in cause the main chart to be called twice (once during the standard update, again during the onBrush() update).  This patch makes those two updates to the main chart mutually exclusive, based on the focusEnable flag.
The majority of the diff is whitespace, now that the focusChart logic is wrapped by an if.  
A few other changes are along for the ride:
* The background rects are now added with the rest of the skeleton code instead of (confusingly) later in the code.
* Avoid creating a local variable called 'that' on general principal.  It was only used in one place.
* The scatter model now offers an option for the interactiveUpdate duration - it had been hard coded to 300ms.  On my machine, that deferred update was taking 8ms …

Performance improvements for lineChart

---

.travis.yml
README.md
src/models/lineChart.js
src/models/scatter.js
test/mocha/line.coffee

I made a significant and terrible mistake with #1245.  In essence, I messed up the Travis CI configuration file such that *only* Meteor tests were being run as a part of this project's continuous integration.  This PR fixes my Travis mistake and attempts to clean up the resulting collateral damage.
Perhaps fortunately, there was only one "bug" (according to the current suite of mocha tests) introduced between #1245 and now.  It looks like #1282 introduced a bug where axes were not rendered on a line chart if `focusEnabled` was set to `false`.  There is a patch in `lineChart.js` in this PR to fix that.
On a lesser note, #1290 changed how series are classed in a scatter model which, in effect, doubles the number of `<g>` elements that receive a class from a data parameter in a line chart. …

Fix Travis CI then Fix Bugs and Tests

---

src/models/stackedArea.js

I don't know why *defined()* exist in line chart but not in stacked area chart but I needed it. So here comes this PR where I added it.
I tested it on several stacked area chart and it works fine.

Add defined to stacked area chart

---

src/models/stackedAreaChart.js

By default headerFormatter will return the xAxis.tickFormat() anyway
Fixes #1081, fixes #1218

Send raw x value to interactiveLayer.tooltip

---

src/models/lineChart.js

typical graph object was of type 
```{key: "some Key",
area: true,
values: [valuesWentHere]}```
I've added a property ```disableTooltip``` to allow for the dispatch event for tooltips to see if tooltips are enabled for that specific series

issue #1301 disable tooltip for specific series

---

src/models/bullet.js

Currently,  markers in bullet charts are positioned when the chart gets created. Afterwards the marker positions are untouched which can cause displacements when for example resize the browser screen.
This pull request moves the translate attribute handling from gEnter to g.

Reposition bullet markers on resize

---

src/models/lineChart.js

I had to modify lineChart's state manually and couldn't access it, though I could access state of other chart models. I looked up the sources and found that instead of exposing lineChart's state there's just blank line.

Expose lineChart's state

---

src/models/axis.js

If you set staggerLabels to true and decide to change it to false later, chart won't update the labels and they remain staggered forever.
This should close issue https://github.com/novus/nvd3/issues/80

Fixed turning off staggerLabels after they have been previously turned on

---

src/models/multiBarHorizontalChart.js
test/multiBarHorizontalChart.html

Clamp YScale on MultiBarHorizontalChart so that graph does not exceed the graph area when forceY option is enabled.
I raised this issue #1425 and fix this issue referencing @mgalloue 's comment and how other nv.models did.(eg. discreteBarChart, boxPlot Chart)
And I added test code on test/multiBarHorizontalChart.html. But this file did not work because wrong file reference, so I fix it together.

Clamp YScale on MultiBarHorizontalChart

---

src/models/multiChart.js

Call to headerFormatter() is missing and tolltip header isn't formatted with the function xAxis.tickFormat()

fix multiChart.js tooltip

---

examples/linePlusBarChart.html
src/models/linePlusBarChart.js

1. The x axis scale was broken in case the option was initially enabled
2. The tooltip formatting was broken and used the wrong tickFormat
3. The horizontal rules for y2 axis were not drawn in case the option is enabled and the lines had no values

Fixed some bugs with the switchYAxisOrder option in linePlusBarChart

---

src/models/pieChart.js

The available width and height were determined by using the width and height of the parent element. This is incorrect behaviour if the width and height are explicitly set. Width and height are inherited properties are should be accessed by referencing pie instead of use width and height directly (which would result in undefined).
Pull request fixes the issue by referencing the pie width and height instead of the pieChart width and height.

pieChart.js: fixed issue with regards to width and height not being used. (Scaling issues)

---

src/interactiveLayer.js

Applied and tested fix as proposed by @slestang
Tested under Google Chrome 47.0.2526.73 m (64-bit) / Windows 7 (x64).
Tooltips now hide after switching browser tabs (as soon as mouse focus returns to the tab containing the chart)

Bug fix for #1263 Tooltip doesn't hide

---

src/models/scatter.js

We've been using nvd3.js at Learning Science Ltd. for plotting continuously generated data, and found the performance of updating a chart to reduce dramatically as the total number of data points increased.
Through some profiling I attributed this to the scatter model (used by most models). The performance is proportional to the total number of nodes because of some unnecessary operations to the D3 update selection.
I have carefully removed or moved operations that do not need to be called on existing nodes and culled the remaining ones by adding some caching (e.g updating position). I've tested the affect of each where possible.
This passes the unit-tests and I have done a side by side comparison of the examples including interactivity. My performance tests show vastly reduced overhead …

Optimise scatter model

---

src/models/bullet.js
test/mocha/bullet.coffee

Currently it's only possible to define three ranges (min, mean, max). It might be quite usefull to define an arbitrary number of ranges.
Also, the existing code sorts the values in descending order,  but leaves the label Arrays untouched. This might cause some confusion when the values are not already provided in the right order.
This pull requests allows to define an arbitrary number of ranges and keeps the labels in the right order. If no range labels are provided, the code falls back to the previous defaults (Minimum, Mean, Maximum).

Allow an arbitrary number of ranges and sort labels accordingly to their values in BulletChart

---

src/tooltip.js

Updating the chart with new data while the tooltip is displayed would (sometimes) cause a new tooltip element to be created. My experience was specifically with a line chart. This fixes that issue.

fix tooltip duplication bug with proper enter/update/exit pattern

---

src/models/pie.js

Currently, the pie chart is a little bit smaller than the available width because of the growOnHover option. If this option is set to false, do not reduce the pie size.

If growOnHover is set to false, do not reduce the pie chart space.

---

src/models/stackedAreaChart.js

For the purpose of having more data in the contentGenerator to make even more customizable tooltips in stackedAreaChart.
Would also be great in other charts.

more data for more flexible custom tooltip

---

src/models/stackedArea.js

I noticed that stackedArea.scatter.forceY can't ever be user set because it always get hard set to [0]. Since there is code to default it to [0] right above I figured this must be an error.

Fix for forceY on stackArea.scatter always getting set to [0]

---

src/utils.js

Not entirely sure why this happens, but we update charts in response to user selectable options, and sometimes the "font-size" style is not yet set on the relevant text element during the update, resulting in an error on the console. Don't know if this is just a band-aid over some other underlying problem, but it at least gets rid of the error.

Change calcApproxTextWidth to return 0 if fontSize is NaN

---

src/models/axis.js

A quick fix for #1475. This is the safe and simple solution of resetting the transform attribute on xTicks before doing the textHeight calculation. I didn't notice any rendering issues because the transform reset didn't have any visual impact when I stepped through with a debugger.
I also played around with an implementation that took advantage of the persistence of the transform attribute, but it seemed like it could easily regress down the road since a lot of attributes on other elements get reset on every update.

Reset tick transform attribute before rotateLabel calculations

---

examples/documentation.html
src/models/axis.js

Simple font-size override option for axis labels. I think in the future it could also allow a function override for more responsive behavior.

Add fontSize option for axis labels

---

examples/documentation.html
src/models/parallelCoordinatesChart.js

- User can customize text displayed for NaN values in a tooltip
- Undefined is displayed by default.

Do not display "NaN" in tooltip

---

src/css/main.css

There is an issue when printing the discrete bar chart from Firefox where the bar label text gets garbled (see attached screenshots). This small css change resolves the issue.

fixed issue when printing from firefox

---

src/models/stackedAreaChart.js

variable 'stackedValue' was renamed to 'point.display' but old variable name was used.

StackedAreaChart bugfix: Corrected wrong variable name in use.

---

build/nv.d3.js
examples/documentation.html
src/models/sparkline.js

I noticed that the `sparkline` model helpfully shows the minimum and maximum points, as well as the current point. For users wanting the ability to toggle the display of these points, I've added simple boolean setter/getter methods that allow that option.
So for instance, someone wanting to show the current point (which defaults to `true`), but not the min/max points, could simply call:
````
var chart = nv.models.sparkline()
.width(400)
.height(30)
.showMinMaxPoints(false)
````
It seems helpful to allow users this option if they choose.

allow boolean options for showing min/max points and current point

---

src/models/linePlusBarChart.js

Corrected bug in lineplusbarchart where multi y-axis tickformat is getting switched with other y axis.
For Example:
Bar chart tooltip y2Axis would have y1Axis tickformat, while line tooltip
would have bar chart y1Axis tickformat.
Note that the both y1Axis and y2Axis would have the correct format, but
the tooltip mouse over for each would be SWITCHED.
Solution:
Logic error in retrieval of barchart and linechart axis during mouse over
event.

Corrected lineplusbarchart mouseover tooltip event where y1Axis and y2Axis are switched.

---

src/models/multiChart.js

Otherwise the header has the raw data, unlike with the "old" tooltip
Steps to reproduce:
- Add `chart.useInteractiveGuideline(true);` to `examples/multiChart.html`
- Add formatting to x-axis, for example `chart.xAxis.tickFormat(d3.format(',.1f'));`
In the current `master` branch you can see different formatting on tooltip's header and x-axis. With this fix, the formatting is the same in the interactive tooltip and the x-axis.

Format MultiChart's interactive tooltip's header with headerFormatter

---

src/models/stackedAreaChart.js

This commit improves the behavior of the StackedAreaChart tooltip by handling
null values consistently with the other charts (i.e. display "N/A" when the value
is null).
Additionally, the "TOTAL" in the tooltip is only shown if there are non-null values.

StackedAreaChart tooltip improvements

---

examples/pieChart.html
src/css/tooltip.css
src/models/pie.js
src/models/pieChart.js
src/tooltip.js

This commit adds an option to the pieChart model which allows the user
to choose whether to show the percentage taken by the hovered slice
in the tooltip.

Add option to show percentage in pieChart tooltip

---

src/models/multiChart.js

Fixes issue #1156 by using similar approach as in #1398 
Related to #1247, #1249, #1210

Fixed #1156: multiChart tooltip valueFormatter is always overriden

---

examples/lineChart.html

This caught me a second time, and still trips people up who follow the advice to download the repo and run examples locally.

transitionDuration is obsolete

---

src/interactiveLayer.js

Check for activeXobject on window object, will return false for IE11

Fixes  #1692 (isMSIE bugfix breaks tooltip in IE11)

---

src/models/cumulativeLineChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/multiBarChart.js
src/models/multiChart.js
src/models/stackedAreaChart.js
src/tooltip.js
src/utils.js
test/bootstrapModalTest.html
test/translateTest.html

FIxes #1532.
This fix corrects the position of the tooltip based on the translate property of the parents.
https://jsfiddle.net/genhmq3v/1/

Fix bug with tooltip positioning.

---

src/models/linePlusBarChart.js

The Change reverts #1518.
The result of this change is that the `tooltip` and `ticks` are always flipped. (`y1Axis.tickFormat` used by the `tooltip` in `y2Axis` and vice versa)
Because `getBarsAxis` und `getLinesAxis` are only used by the tooltip it shouldn't affect anything else.
Example (`nvd3-community`-Example against `1.8.3`)
http://plnkr.co/edit/aJ0BLI8QPBLprXTtpokV?p=preview
Example with fix applied:
http://plnkr.co/edit/MTsl4q9fiobyHUZVUaOm?p=preview
Alternatively just revert the commit. ;)

linePlusBarChart: tooltip and ticks have are flipped axis (Reverting #1518)

---

src/models/linePlusBarChart.js

@liquidpele while trying to customize the line width in a linePlusBarChart, I noticed the `stroke-width` of the line is unaffected although the property `strokeWidth` is set on the chartData. This PR should fix the bug.

linePlusBarChart: need to pass along "strokeWidth" while rendering line

---

src/models/furiousLegend.js
src/models/legend.js

This commit adds a keyFormatter to the legend and the furiousLegend.
This can be used to format the labels of the legend.

Add a keyFormatter to the legend

---

src/models/lineChart.js

This commit fixes a rendering issue wit the lineWithFocusChart.
When a lineWithFocusChart initially has no data, then gets data and
update() is called, only the focus part is rendered. Only when data is
set again and update() is called again does the 'normal' linechart
show correctly.
Listening for the 'onBrush' event of the focus before initializing the
chart seems to fix the issue.

Fix lineWithFocusChart rendering issues

---

src/models/sunburst.js
src/models/sunburstChart.js

This commit fixes the margin on the Sunburst chart.
Since the sunburstChart.js has no longer a wrapper container,
the margin options are useless. Instead, the margin is now
shared between the sunburstChart and the sunburst objects.
Furthermore, the sunburst.js did not take into account the
margin when calculating the middle of the container.
Also, when the update() function was called the container
did not apply the newly calculated translate() arguments.
Finally, the sunburstChart.js now has the option to show
the percentage of a node in the tooltip, similar to the
pieChart.

Improve Sunburst margin & show percentage on tooltip

---

blog/2014/03/nvd3-issues-triage/index.html

I am getting emails from users with issues. I'd like to remove my email address from this blog post. Thanks.

Remove my email address for blog post

---

src/models/scatter.js

Add a sizeDiff bool that explicitly checks for changes in chart size. The scaleDiff bool used to trigger a full redraw in the optimisation from PR #1378 is not always true when chart size changes.

Fix chart resize bug in scatter model optimisation

---

src/models/multiBarChart.js

allowing users to set valueFormatter for interactiveLayer.tooltip (it was previously being overwritten)
This change should also be implemented on other charts that use interactiveLayer.tooltip

fixing multiBar tooltip formatting

---

src/models/sunburst.js

As stated in https://github.com/novus/nvd3/issues/1531 by @brockj I think the elementClicked is not triggered in sunburst chart.
I hope this fixes it :)

Add the click elementClicked dispatch

---

src/models/bullet.js

The new marker line code merged in from pull request #1699 some days ago does not properly handle redraws of the marker line. The selectAll tries to find a path element although the line is a line element.
Furthermore setting the transform attribute does not make any sense here. Setting x1 and x2 works far better.

Move marker line in bullet chart on redraw

---

src/models/multiBarChart.js

This purpose of this pull-request is consistency between line-charts and bar-charts with regard to the formatting of values within a pop-up tooltip when `useInteractiveGuideline` is enabled.
See [lines 49](https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L49) through [53 of `lineChart.js`](https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L49), where the tick-formatter for the y-axis is used as the value formatter for the interactive-layer's tooltip value-formatter, and which is a repeat of [the immediately preceding stanza](https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L43) where the same y-axis value formatting is assigned for use by the tooltip when the interactive-layer is absent.
The first of these two line-chart stanzas currently …

Make multiBarChart defer to y-Axis tick format for interactiveLayer tooltip value formatting

---

src/models/lineChart.js

Fixes a “TypeError: Cannot read property 'x' of undefined” error when
using the interactive guideline for line charts if the extent is not in
ascending order.
In our use case, we reversed the x-axis on the line chart by reversing
the x domain.  This caused series.values.filter to filter out all our
values and result in the TypeError when calling interactiveBisect  A
check was added to ensure the extent is in ascending order.

fix: Line chart interactive guideline error when extent is not in ascending order

---

src/models/scatter.js

When determining if point positions need updating the optimisation in the scatter model checks for differences with "x" and "y" point keys. Alternative keys "0" and "1" appear to be used in some cases too.
Fixes #1814

Fix point update bug in scatter model

---

src/models/focus.js

@liquidpele See discussion [here](https://github.com/novus/nvd3/issues/1243) and [here](https://github.com/novus/nvd3/issues/955). This is a "quick and dirty" fix in that it simply removes the offending lines.

Fix 1243: LineWithFocus: chart doesn't update if the focus area is less than 1 even if chart is all decimals

---

src/models/multiBarChart.js
src/models/pieChart.js

- PieChart : add a legendPosition 'bottom' in addition to 'top' and 'right'.
The bottom margin become the height of the legend. The legend is translated to the bottom of the graph, using the available height.
- MultiBarChart : add a legendPosition. The position can be default (top) or 'bottom'.
The legendPosition field is new. If not set, keep the current behavior. The bottom margin become the height of the legend plus the height of the x-axis legend. The legend is translated to the bottom of the graph, using the available height plus the height of the x-axis legend.

Add a 'bottom' legend to PieChart and MultiBarChart

---

src/models/scatter.js

Unselecting a legend item doesn't always cause the voronoi paths to be cleaned, resulting possibly in leftover tooltips. See report in #1664

Fixes #1664

---

package.json

Make NVD3 development more build system agnostic. There are many node
build systems, not every project uses the same one, we shouldn't have to
remember which one or need to globaly install it's CLI.
npm adds ./node_modules/.bin to the run $PATH, so we can add grunt-cli
to the local dependencies. Contributors are free to use generic "npm run
build" commands without knowing or remembering grunt.

Add grunt-cli to package.json for local build

---

examples/documentation.html
src/tooltip.js

I'm using angular-nvd3, where I absolutely need to use Angulars Data Binding within the tooltip.
For this to work, I needed to manually call $compile() with my html template. For the non Angular people here: $compile creates DOM Elements and adds watchers/event handlers/etc... for Angular. 
Overwriting the contentGenerator() method only allows you to return a string (basically HTML), while the comments on the method clearly say:
```javascript
initTooltip();
// Generate data and set it into tooltip.
// Bonus - If you override contentGenerator and return falsey you can use something like
//         React or Knockout to bind the data for your tooltip.
var newContent = contentGenerator(data);
if (newContent) {
tooltip.node().innerHTML = newContent;
}
```
I wonder why it says here that you can …

Provide tooltip element to contentGenerator to allow custom tooltips to access this element

---

src/models/legend.js

Many users were asking for possibility to disable only double click events on legend. For the time being there is only flag resposible for disabling all kind of click events. Expected behavior can be achieved by adding new flag `enableDoubleClick`.

Issue 1666

---

src/models/scatter.js

- **Comments** - For implementation decisions and optimisations (Requested by @liquidpele in #1817)
- **Formatting** - Conservative tidying of concerned code for legibility
- ~~**Performance** - Remove duplicate point enter/exit code (credit to @PeterVermont from #1814)~~
- **Fix** - A subtle edge case with invalid caches
The removal of the duplicate code warrants some thorough testing, it does appear to be unnecessary but it's possible it was there for a reason. The change passes all unit tests and at a glance everything seems ok. I'm gradually going through the examples in painful detail, (other testers are welcome).

Scatter Model Maintainability

---

src/models/pie.js
src/utils.js

Not to display overlapping labels
Before
After
Credits
http://stackoverflow.com/a/19801529/2697673

[pie-chart] Fix label overlap

---

src/models/multiChart.js

This commit introduced a subtle regression:
https://github.com/novus/nvd3/commit/9b75644ebc5c15caa2bb803e8d5612e1463caf5b#diff-b5254de5addcaf88c0900e46af95e3d7
Before it, `{x:0, y:0}` would get added to the `extraValue` only if `dataBars1.length`. The change made non-stacked bar charts behave differently.

Restore pre #1554 behaviour of bars that go down to 0 by default

---

src/models/cumulativeLineChart.js
src/models/scatter.js
test/mocha/cumulative-line.coffee

The cumulativeChart is actually an index chart, see [http://mbostock.github.io/protovis/ex/index-chart.html](http://mbostock.github.io/protovis/ex/index-chart.html) (I think, the name should be changed some day).
However, the first thing should be to correct the math: the `y` axis shows the percentage of `y_i` relative to the index value `v`. So the right formula is `(y_i - v)/v` (as also used in Mike Bostocks code) and not `(y_i - v)/(1 + v)`

modify indexify to divide by v and not by v+1

---

src/models/cumulativeLineChart.js

The fixed behavior is like this:
- There is a new private variable `currentDomain` which holds the yDomain in the non-rescale case
- This variable will be initially set after the first call to `indexify`
- When the rescale control is disabled by the user (i.e. no rescale) then the yDomain of the currently selected index point is retrieved (by a new function `getCurrentDomain`) and stored in currentDomain.
- `currentDomain` is used in non-rescale case to set `lines.yDomain`
- Additionally tooltip don't show values of `tempDisabled` series and `rescaleY` option also sets `state.rescaleY`

fixed rescaleY behaviour

---

src/models/multiChart.js

Added new option `xScale` to multiChart graph solvind the issue 
```
chart = nv.models.multiChart()
.margin({ right: 23, top: 12, left: 60, bottom: 75 })
.showLegend(false)
.xScale(d3.time.scale.utc())
```
This may close #814

added xScale option for multiChart graph

---

src/models/scatter.js

This is a bugfix for zooming when the guideline is off. When hovering over a point, zooming in such that the mouse leaves the selection area of the point would not remove the point's highlighting. This resulted in the point being permanently highlighted:
This was fixed by clearing any highlighted points on mouse move, before it chooses a new one to highlight.

Fixed scatter point highlighting persistence on zoom

---

src/models/lineChart.js

This is a fix for #2024.  When zooming or panning to the right, if the leftmost visible point is not the first index, the wrong points are highlighted when the interactiveGuideline is enabled. As mentioned in that issue, this fix should not affect the case described in the comment, as it checks the indexes after that case is handled. This changes the passed index from the point's index of the filtered array to its index in the full series.

Fixed point highlighting on line chart after zoom or pan

---

src/tooltip.js

The old code:
tooltip = d3.select(document.body).select('#'+id).data(data);
Added the tooltip div outside the Body tag, which then led to translation tools not finding the tool tip text.
This is also not valid HTML
By using:
tooltip = d3.select(document.body).selectAll('#'+id).data(data);
The tooltip div is once again inserted inside the body tag, where it should be.

Fixed bug where tooltip would be inserted outside Body

---

README.md

Save users some searching by having a direct link to the source for the most recent version of d3 v3.

added link to most recent d3 v3 release

---

GruntFile.js
src/models/lineChart.js

Fixes #2018.
Issue is that the scatter layer is watching a transition to synchronize point updates (`transform` attribute) [here](https://github.com/novus/nvd3/blob/master/src/models/scatter.js#L537).
But the `lineChart` (the parent container) is not initiating the call via a `transition` (like the [scatterChart](https://github.com/novus/nvd3/blob/master/src/models/scatterChart.js#L101) and other charts), therefore the point transform attributes aren't updated.
This PR fixes that and makes the `lineChart` behavior consistent with the other charts.

Fix points position update on line chart

---

src/models/stackedAreaChart.js

Bottom legend on stackedAreaChart doesn't accommodate for full X axis vertical spacing and overlaps legend with label.
This PR fixes it in a manner that is consistent with the other chart types that support bottom legend (lineChart, multiBarChart, multiBarHorizontalChart).
Before:
After:

Fix legendPosition bottom on stackedAreaChart

---

examples/scatterChart.html
src/models/scatterChart.js

current `scatterChart.js` does not allow for updating the `showDistX()` & `showDistY()` options after a chart has been drawn; this PR always generates the DOM elements for the axis distributions and does a `watchTransition()` on them to properly set the opacity.

allow x/y distribution to update on chart option change

---

src/models/scatter.js

I probably have a specific use-case, but I am using a chart linked to a map, when the map is moved/zoomed I update the data of the chart and I noticed that the labels in my scatterChart were not updated accordingly. 
I noticed that the locations of the labels where changed correctly but the text-contents where completely random. I assumed this has to do with the fact that the default identifier is the location in the array. I added an `id` field to my data but this did not help at all. 
So I am a bit stumped why the id was not taken into account (it never is/was?), so the easy fix was also update the label's text contents on update. 
This is a pretty small change, do you need anything else to be able to merge this?

Update (existing) label texts for scatter-plots

---

src/models/stackedAreaChart.js
test/mocha/stacked.coffee

Stream center option works better for datasets including zero
#416

feat($stacked-area): Support Stream_Center as control option

---

src/models/axis.js

No consideration was given to positioning the axis label in the `top` orientation - this fixes that by using the same label positioning as `bottom`, but in the negative direction.

axis.orient('top') label spacing fix
