novus/nvd3

.travis.yml
README.md
bower.json
package.json

Updating package.json so that on postinstall it will do bower install.

---

src/models/axis.js
test/mocha/axis.coffee

i'm handling: https://github.com/novus/nvd3/pull/114

Axis rotation alignment bug: Fixing Pull Request #114 manually

---

src/models/pie.js
test/pieChartTest.html

Related pull request: https://github.com/novus/nvd3/pull/647
But this one is from an up-to-date development branch.

bugfix - donut outside labels should follow the start - end angles #647

---

src/core.js

Also adding some better comments explaining nv.addGraph

Fixing issue #279: removing arguments.callee, which is deprecated.

---

GruntFile.js
package.js
package.json

Hello guys,
As you might know, the Meteor community is widely using nvd3. We had many different wrapper packages all doing the same thing, so I'm submitting a PR that integrates Meteor packaging directly into your repository: at the end of this merge process, in case you'll find yourself comfortable with it, we'll get automated new Meteor package releases with every new release of nvd3.
I've made this PR as lean as possible so as not to take up too much space within your repository: basically it adds only a package.js file among the ones already present for other package managers.
All you have to do after accepting this PR would be:
Create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and we'll …

Meteor Integration

---

src/models/scatterChart.js
test/mocha/scatter.coffee

This code change cleans up the logic in scatterChart.js surrounding the legend.  Adding some unit tests.
Issue #777

Issue #777: Scatter Chart legend bug causing clipping issues

---

test/ScatterChartTest.html

https://github.com/novus/nvd3/issues/773

Issue #773: Updating scatterChartTest html page so that more axes lines show up

---

examples/legend.html
src/models/legend.js
test/mocha/legend.coffee
test/mocha/test-utils.coffee

Fixing bug where legend double clicking seemed to break when updating chart data. Issue #784 reported this.
This PR adds proper unit tests and fixes the issue.

Issue #784: Legend dblclick and click handlers

---

src/models/axis.js
src/models/discreteBarChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
test/mocha/axis.coffee

Adding unit test to check for the 'zero' tick in axes.
Issue #410

Issue #410. Replacing this.__data__ with bound variable 'd'. Removing  highlightZero option.

---

examples/site.html
examples/sunburst.html
src/css/tooltip.css
src/models/sunburst.js
src/models/sunburstChart.js

I tried to re-use the existing tooltip code, but it's way too specific for x-y coordinates and having a mouse following version is stupid simple anyway since it doesn't need any of the extra complexity.

Added a tooltip to sunburst.  

---

examples/multiBarHorizontalChart.html
src/models/axis.js

by getting the max value in scale instead of assuming [0] was the max when calculating the x offset for the axis label.
I did a little code cleanup too, based on warnings in my IDE.  
Also set the example to use axis labels there.

Fixes https://github.com/novus/nvd3/issues/823

---

src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/lineWithFocusChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/stackedAreaChart.js
test/mocha/cumulative-line.coffee
test/mocha/discretebar.coffee
test/mocha/historical-bar.coffee
test/mocha/line.coffee
test/mocha/multibar-horizontal.coffee
test/mocha/multibar.coffee
test/mocha/scatter.coffee
test/mocha/stacked.coffee

Issue #601 fix: allowing axis.ticks() to be overridden in charts

---

examples/documentation.html
examples/legend.html
src/models/legend.js
test/mocha/legend.coffee

Issue 657: legend spacing option

---

examples/documentation.html
examples/pie.html
examples/pieChart.html
src/models/pie.js
test/mocha/pie.coffee

Issue 555: Pie label formatting (also removing 'labelFormat')

---

src/models/scatter.js
test/mocha/scatter.coffee

Issue #783: Need to remove prior nv-point-clips on scatter update.

---

src/models/scatter.js

Shapes show up again in scatter chart.

Fix scatter shapes

---

examples/TimeSeries.html
examples/site.html

Took the jsfiddle example from https://github.com/novus/nvd3/issues/145#issuecomment-76990255 and made an example in the project with it.

Add time series example 

---

examples/documentation.html
examples/monitoringChart.html
examples/site.html
src/models/pie.js

You can have the possibility to customize each slice size, by define an inner and an outer arc radius for each slice (value between 0 and 1). 
You can still use the existing donut ratio if you want.

Add possibility to have different slice size on a pie

---

index.html

[Issue 868](https://github.com/novus/nvd3/issues/868)

Issue 868. Change links to use CDN

---

src/models/cumulativeLineChart.js

Convert cumulative line chart to use tooltip object.

---

src/models/scatter.js

Verified this fixed the voronoi multi-point issues on stackedareachart.  A better solution should probably be thought up, but at least this makes the chart not break for the time being.

Fix voronoi when multiple series have the same poin

---

build/nv.d3.js

This is still WIP making nvd3 work in touch devices

Enable interactiveLayer mouseHandler on touch event

---

build/nv.d3.js

Revert "Enable interactiveLayer mouseHandler on touch event"

---

src/css/bars.css

Css bugs (zfill class, where did that come from?)

---

examples/documentation.html
src/tooltip.js

add support for configuring tooltip offset

support tooltip offsets from pointer

---

src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/lineWithFocusChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/multiChart.js
src/models/scatterChart.js
src/models/stackedAreaChart.js
src/utils.js

https://github.com/novus/nvd3/issues/895
THIS IS NOT COMPLETE.   I'm making this pull request for discussion as a possible solution.  
What this does is it actually makes each chart create a duplicate of each option named the same with an underscore prefix (which is thus hidden in the docs).  Calling the underscore version will be IGNORED if the non-underscore version has been called at some point.  This allows nvd3 to change it's own options internally up until someone changes the option manually from code outside of nvd3.  
Thoughts?

Possible fix for axis not rescaling. 

---

src/models/pie.js

Added working custom pie chart labels

Custom Pie Chart Labels

---

src/models/historicalBarChart.js
src/models/lineChart.js
src/models/lineWithFocusChart.js

Solution with customized tooltip (in some case) needs the pointIndex to access original data set to display proper information. 
Thx

lineChart (historicalBarChart and lineWithFocusChart) - customized tooltip 

---

src/models/line.js
src/models/scatter.js
src/utils.js

This is a subset of the changes from https://github.com/novus/nvd3/pull/798.
@liquidpele, @robinfhu, could we sneak these changes in to 1.8.1?

Avoid voronoi vertices when not used

---

examples/boxPlot.html
src/css/boxplot.css
src/models/boxPlot.js
test/boxPlotTest.html
test/mocha/boxplot.coffee

This PR includes a few small improvements:
* Better handling of bad data values for whiskers and outliers
* Mouseovers for whiskers
* Slight changes to the example boxPlot.html
* New bad data tests in boxPlotTests.html

Improvements to boxPlot charts. 

---

src/models/lineWithFocusChart.js

I forgot about the getters - and my original PR already got merged before I could amend :stuck_out_tongue:

LineWithFocusChart: Fix also the tickformat getters

---

examples/multiBarChart2.html
src/models/multiBar.js
test/multiBarChartTest.html

- exit transition for nonstackable series
- applied group view for multi-nonstackable series
- fixed yDomain range issue where there is nonStackable series
- fixed nonStackable and stackable position issue when nonStackable series it's not the last series.

Bug fix for the nonStackable feature for multiBar model

---

examples/multiBarChart.html
src/models/multiBar.js
src/models/multiBarHorizontal.js

Also added the 'errorBarColor' option to both MultiBarChart and MultiBarHorizontalChart

Support for error bars in MultiBarChart

---

examples/TimeSeries.html

Fixed overlapping bars when there are gaps. Fixed the first and last bar to not get cut off. Improved gap generator. Two styles of bars: x ticks centered on the bars vs x ticks at the bar edges. They are meant to differentiate between the meaning of the bars: bars that represent a point in time versus bars that represent a span of time.

Improvements to the time series example

---

src/tooltip.js

Fix for https://github.com/novus/nvd3/issues/1085

Fix for IE9 tooltip positioning

---

index.html

Somehow related to the https://github.com/novus/nvd3/issues/1059

Update documentation to the latest version

---

examples/multiBarChart.html
src/models/multiBar.js
src/models/multiBarHorizontal.js

Revert "Support for error bars in MultiBarChart"

---

src/models/multiBar.js
src/models/multiBarChart.js

Attempting to fix #1121. This fixes the issue in my case, not sure about side effects of this fix.

Fix proposal for #1121

---

src/models/scatter.js

Fixes #1147
This patch fixes data rebinding when highlighting points in the scatter
model.

scatter.highlightPoint is broken

---

src/models/candlestickBar.js

If the data changed the candlestick would plot the candles in the wrong place. Now this is fixed.

Fix bug with the candlestick chart.

---

src/models/scatter.js
src/models/scatterChart.js
test/mocha/scatter.coffee

Fix #1164: scatter mouseover wrong position.

---

src/models/multiChart.js

Show the key label in multichart when a line serie is enabled

fix tooltip key label in multichart (line series)

---

src/models/multiChart.js

Now all keys (curve names) where displayed in multiChart tooltip. See sample file ./examples/multiChart.html

Multi chart tooltip fix

---

src/models/legend.js
src/models/multiChart.js

This change allows the rendering of dates in multiChart as described in issue #1228.  It adds a config option called xAxisDates.

Allow rendering of dates on X axis in multiChart

---

src/models/discreteBarChart.js

Add rotateLabels for discreteBarChart

---

src/tooltip.js

Add deprecated messages for tooltip options that were removed.

---

src/models/discreteBarChart.js

Added the option to showLegend 

---

src/css/pie.css

making pie chart slices darker on hover over

fix for https://github.com/novus/nvd3/issues/1252

---

src/models/lineChart.js
src/models/sunburst.js
src/models/sunburstChart.js

fix for https://github.com/novus/nvd3/issues/1145

adding update function for sunburst model,

---

src/models/discreteBarChart.js

fix: zero line in discreteBarChart model

---

src/interactiveLayer.js
src/models/multiBarChart.js
test/mocha/multibar.coffee
test/multiBarChartTest.html

I needed to useInteractiveGuideline with multiBarChart but it was missing. I think it might be useful for some people.

Added useInteractiveGuideline option to multiBarChart

---

src/models/multiChart.js

There is no interactive guidline in multiChart and the existing tooltips are a bit cumbersome to use. So this might be an implementation mostly inspired by lineChart.

Add Interactive guildline to multiChart

---

src/models/parallelCoordinates.js

Stroke width property doesn't work on parallelCoordinate chart because variable is badly named, so I renamed it. Sorry, my bad.

Fix issue on Stroke width

---

examples/documentation.html
examples/linePlusBarChart.html
src/models/linePlusBarChart.js

Hey,
this is a resubmit of https://github.com/nvd3-community/nvd3/pull/54 updated to the new nvd3 version. For details and example screenshots please see the previous pull request.
Best regards,
Chris

Added option to switch lines and bars yAxis in linePlusBarChart

---

src/models/parallelCoordinates.js
src/tooltip.js
src/utils.js

Typo: Fix issue on brush badly resizing in a particular case (with only NAN values on a dimension).
Typo: Fix issue on drag axis (available width doesn't exit, use width instead)
Update availableHeight and availableWidth function to avoid negative values (use zero instead).

Fix a few issues

---

src/models/multiBarHorizontalChart.js

controlLabels doesn't work with multiBarHorizontalChart

fix issue #1411

---

src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/multiChart.js
src/models/parallelCoordinatesChart.js
src/models/pieChart.js
src/models/scatterChart.js
src/models/stackedAreaChart.js

I've accidentally deleted #1413. It's a pure copy. @liquidpele, please, check it.

remove Controls if showControls=false (repeat #1413)

---

src/models/pieChart.js

Revert "Add missing options / Fix sizing issue"

---

examples/documentation.html
src/models/sunburst.js
src/models/sunburstChart.js

Hi,
I was actually trying to fix the updating of the sunburst chart (https://github.com/novus/nvd3/issues/1317), but utterly failed.
But along the way I cleaned up some stuff and added some other functionality.
- customizable labels
- tooltip value formatter as parameter
- sort parameter to specify the order of the arcs 
Labels were requested in this issue: https://github.com/novus/nvd3/issues/1284

Some changes/enhancements to Sunburst chart

---

src/tooltip.js
src/utils.js

should fix http://github.com/novus/nvd3/issues/1448

Make helper functions to handle browser quirks

---

src/models/lineChart.js

Use chart.interactiveLayer.tooltip.valueFormatter in lineChart [fixes #303]

---

examples/documentation.html
examples/parallelCoordinates.html
examples/parallelCoordinatesChart.html
src/models/parallelCoordinates.js
src/models/parallelCoordinatesChart.js
src/models/scatter.js
src/tooltip.js

Update PR according to feedback on PR [#1393](https://github.com/novus/nvd3/pull/1393).

Parallel chart improvements

---

examples/boxPlot.html
examples/boxPlotCustomModel.html
examples/site.html
src/models/boxPlot.js
src/models/boxPlotChart.js
test/boxPlotTest.html

- Extending Box Plot model to support attribute accessor callbacks for custom models.
- Model remains backwards compatible with original data structure implementation (e.g. `label, values, outliers`, etc.). `y` chart option now emits a deprecation warning to the developer.
- Adding support for outlier elements as objects including label, color and value.
- Updated Box plot test case page.
- Cleaned up JSHint linter warnings for Box plot model.
- Updated examples page with existing and new example entry.

Extended object attribute access for Box Plot model.

---

src/models/parallelCoordinates.js

I need to define available width and height as global variables because it is used on the drag function and it can change during a chart update.

Fix dragging issue

---

src/models/discreteBarChart.js

found duplicate code and removed it.

removed duplicate code

---

src/models/pieChart.js

Reverts novus/nvd3#1408
Reverted due to https://github.com/novus/nvd3/issues/1481

Revert "pieChart.js: fixed issue with regards to width and height not being used. (Scaling issues)"

---

examples/documentation.html
src/models/line.js
src/models/lineChart.js

Revert "Areapath stuff"

---

src/models/multiChart.js

Fixes issue https://github.com/novus/nvd3/issues/1501

Added interpolation for area charts in Multichart type

---

src/models/parallelCoordinates.js
src/models/parallelCoordinatesChart.js

DimensionsName is a duplicate of DimensionData so I remove it to clean the code. Also the loop for currentPosition and originalPosition is not necessary.

Remove unnecessary duplicate object

---

src/models/multiChart.js

Fix interpolate set to wrong mode

---

src/dom.js

fastdom names seem to have changed:
fastdom.write --> fastdom.mutate
fastdom.read --> fastdom.measure

Fix names of fastdom functions.

---

src/models/legend.js

Allows legend to update properly even with different symbol shapes.

Allows legend to update properly even with different symbol shapes.

---

src/tooltip.js

crediting @AdamWaz, fixing #1385

fixing tooltip floating-point number precision, fixes #1385

---

src/models/multiBar.js
src/models/multiBarHorizontal.js

As #707 discusses, it'd be nice to have control over the fill opacity for the bar charts

Hand over fillOpacity for bars in multiBar and multiBarHorizontal charts

---

src/models/axis.js

Added the same logic as for left aligned axes.

Added support for axisLabelDistance to right aligned axis

---

src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/multiChart.js
src/models/parallelCoordinatesChart.js
src/models/pieChart.js
src/models/scatterChart.js
src/models/stackedAreaChart.js

Overwrite the top margin & availableHeight only in case the legend's height is bigger than the top margin.

---

src/models/multiChart.js

Adds a `transitionDuration` option to multiChart model that affects the transition duration of the axes and lines of the chart.

Add transitionDuration option to multiChart

---

src/models/lineChart.js

this is to fix https://github.com/novus/nvd3/issues/1525

fix: revert highlight point index value

---

src/models/focus.js

This doesn't really change anything, just deletes a trailing comma

Delete trailing comma

---

examples/documentation.html
src/models/scatter.js

Added support for scatter chart to change border color

---

src/models/legend.js

this fixes legend translate error: string-int is NaN, should be string+(-int).

fix - d3.min.js:1Error: attribute transform: Expected transform function, "NaN,5)".

---

examples/documentation.html
src/models/focus.js

Add 'syncBrushing' option on focus component

---

src/models/cumulativeLineChart.js
src/models/discreteBarChart.js
src/models/historicalBarChart.js
src/models/lineChart.js
src/models/linePlusBarChart.js
src/models/multiBarChart.js
src/models/multiBarHorizontalChart.js
src/models/multiChart.js
src/models/parallelCoordinatesChart.js
src/models/pieChart.js
src/models/scatterChart.js

fixes graph not resizing when legend becomes smaller than the top-margin
issue https://github.com/novus/nvd3/issues/1764

- fixed graph not resizing 

---

src/models/lineChart.js
test/mocha/line.coffee

Fixing issues where focus chart did not hide properly when toggled off, and selected range would reset.

Line chart focus enabled toggle

---

src/tooltip.js

the data in a series might have additional information contained on a per point basis that is useful to display. this diff exposes the original data point to the valueFormatter as a third param

pass point to tooltip valueFormatter as third arg

---

examples/sunburst.html

Fix for [1924](https://github.com/novus/nvd3/issues/1924)

Fix for string "data" not showing in sunburst chart.

---

src/models/lineChart.js

fix: [https://github.com/novus/nvd3/issues/1878](url)

fix for #1878

---

examples/multiBarHorizontalChart.html
src/models/multiBarHorizontalChart.js

Here is a P.R. for a proposal to add legend position to the Horizontal Multi Bar Chart, similar to how we can control the position on the lineChart.  See issue #1902 
cc: @liquidpele

Added bottom legend and bottom controls to horizontal multi bar chart. #1902 

---

src/interactiveLayer.js

See linked issue. Not sure if this is a clean solution, but it does fix the problem.

fix interactive guideline offset for Firefox, fixes #1953

---

src/models/stackedAreaChart.js

The change is to show points for data which has value greater than zero. So, if only one of all the elements of the data array has a value greater than zero, then only one point will be shown.
If all values are zero, then we will show one point only with the color of the last Index.

Fix for #1876

---

src/models/multiBar.js
src/models/multiChart.js

This is a pull request with the fix suggested in #1653, with some more code to make it work with multiBar. We're running this in production.

Fix multiChart tooltip series yAxis (#1653)

---

src/models/forceDirectedGraph.js

https://github.com/novus/nvd3/issues/1819

add declarations for getX and getY in force directed graph

---

src/models/multiChart.js

Fix For #1959

---

src/models/stackedAreaChart.js

Added the logic for variable atleastOnePoint.

Fix one part of #1963. Missed Logic added.

---

src/models/lineChart.js

removed tooltipshow and tooltiphide.

removed deprecated references

---

examples/distroPlotChart.html
examples/documentation.html
src/models/distroPlot.js
src/models/distroPlotChart.js

This is an update for PR #2070 that includes:
- object constancy fix during transitions
- disable legend (don't think it makes sense for this type of plot)
- add observation count info to tooltip
- whisker distance calculation now correct 😳 
- extend y-axis with `.nice()`
- bug fix for yscale when using beeswarm
- bug fix for observation opacity during updates
- disable tooltip for hidden observations

Distrochart

---

src/tooltip.js

Change to position: absolute instead of position: fixed
#1463

fix($tooltip): Fix issue with tooltip not hiding when scrolling

---

src/models/lineChart.js
src/models/scatter.js

While playing around with with the scale and range values to implement a zooming functionality, I encountered a few errors, so I added some additional checks in order to avoid them. It would be great to have them on the main branch!

Fix errors when zooming on data
